#! /bin/sh

#The location of the Titan application binary must be included in the PATH environment variable.  
# vhub (Note: On VHub, the location of the Titan application binary is set via HUBzero invoke processing when the Titan2D tool GUI is launched).  Example:
# use titan2d-v4.0.0-alpha5
# rush:
# module load titan
# otherwise:
# Add the path to the Titan application binary to the PATH environment variable.
# Example, in your .bashrc file:
# export PATH=$PATH:"/projects/academic/gmfg/renettej/titan2d_github/titan2d/bin"

# Note: on VHub, the TOOLDIR environment variable is set via HUBzero invoke processing when the Titan2D tool GUI is launched.  Need TOOLDIR defined to create KML files.  Setting TOOLDIR to the parent directory.
export TOOLDIR="$(dirname "$(pwd)")"
echo $TOOLDIR

# Note: on VHub, only 1 node and 1 cpu are allowed per job.
# Default, assumes running titan2d on vhub
export E_VHUB="false"

# Specify the start directory for the directory selectors.
# Default, $Home
# Example:
# export E_INPUTDIR="/projects/academic/gmfg/renettej/titan_java_gui"

fullpath="$(readlink -f $0)"

libpath="$(echo "$fullpath" | sed "s?/bin/run_titan?/bin?")"
helppath="$(echo "$fullpath" | sed "s?/bin/run_titan?/share/doc/titan?")"

export CLASSPATH=${CLASSPATH}:$libpath/titan_gui.jar:$libpath/jh.jar:$libpath/derby.jar:$helppath

java titan.gui.Titan
